export interface Env {
  DB: D1Database;
  MEDIA: R2Bucket;
  CHAT_ROOM: DurableObjectNamespace;
  ALLOWED_ORIGIN: string;
  INTERNAL_SECRET: string;
  RESEND_API_KEY: string;
  OPERATIONAL_ALERT_EMAIL?: string;
  APP_ORIGIN: string;
  REPORTS_CHANNEL_ID?: string;
  UNIFIED_TIMELINE_CHANNEL_ALLOWLIST?: string;
  UNIFIED_TIMELINE_LIVE_CHANNEL_ALLOWLIST?: string;
  UNIFIED_TIMELINE_REPORTS_CHANNEL_ALLOWLIST?: string;
  UNIFIED_TIMELINE_SAMPLE_PERCENT?: string;
  UNIFIED_TIMELINE_SAMPLE_SALT?: string;
}
