export interface Env {
  DB: D1Database;
  CHAT_DB_CANARY_A?: D1Database;
  CHAT_DB_CANARY_B?: D1Database;
  MEDIA: R2Bucket;
  CHAT_ROOM: DurableObjectNamespace;
  ALLOWED_ORIGIN: string;
  INTERNAL_SECRET: string;
  VAPID_PUBLIC_KEY: string;
  VAPID_PRIVATE_KEY: string;
  VAPID_SUBJECT: string;
  RESEND_API_KEY: string;
  OPERATIONAL_ALERT_EMAIL?: string;
  APP_ORIGIN: string;
  REPORTS_CHANNEL_ID?: string;
  WRITE_MAINTENANCE_MODE?: string;
  D1_CANARY_PROJECTION_DISPATCH_ENABLED?: string;
  D1_CANARY_PROJECTION_DISPATCH_SHARDS?: string;
  D1_CANARY_OPERATOR_TOKEN?: string;
  D1_CANARY_SHADOW_CHANNELS?: string;
  UNIFIED_TIMELINE_CHANNEL_ALLOWLIST?: string;
  UNIFIED_TIMELINE_LIVE_CHANNEL_ALLOWLIST?: string;
  UNIFIED_TIMELINE_REPORTS_CHANNEL_ALLOWLIST?: string;
  UNIFIED_TIMELINE_GLOBAL_ENABLED?: string;
  UNIFIED_TIMELINE_SAMPLE_PERCENT?: string;
  UNIFIED_TIMELINE_SAMPLE_SALT?: string;
}
